#!/bin/bash

folder_contains_changes() {
  git diff --name-only HEAD HEAD~1 | grep -q "^$1"
}

folder_contains_script() {
  cat package.json | grep -q 'prepush'
}

run_script() {
  if [ -f package.json ]; then
    if folder_contains_script; then
      npm run prepush
    fi
  fi
}

for folder in */; do
  if folder_contains_changes "$folder"; then
    (cd "$folder" && run_script)

    if [ $? -eq 1 ]; then
      exit 1
    fi
  fi
done
